name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload site artifact (v4)
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./dist

  deploy:
    needs: build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # keep the provided GITHUB_TOKEN credentials so the deploy action can push
          persist-credentials: true

      - name: Download site artifact (v4)
        uses: actions/download-artifact@v4
        with:
          name: site
          path: ./site

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          # create/force an orphan branch to avoid fast-forward rejection
          force_orphan: true
          allow_empty_commit: false

